### ISSUE TITLE
Authentication failed while using the copyArtifacts plugin

### ISSUE THREAD

**Issue by IgnacioMS22** [jenkinsci/artifactory-artifact-manager-plugin#85]
Hi,

I am interested in using this plugin since it provides an easy and useful way to archive the build artifacts without changing the archive statement in free-style and pipeline jobs. Currently, I have configured the "Access settings" tab in the Jenkins Global Setting page with my Artifactory OSS settings and I am trying to leverage the same feature to get the archived artifacts from another job using the "copyArtifacts" plugin. When the copyArtifacts statement is performed, the build fails due to authentication is required error as shown below:

```
Failed to download http://<ArtifactoryURL>/artifactory/<repo>/<parent-folder>/<job>/<buildID>/artifacts/.../<artifact-name> to <WORKSPACE>, response: 401 Unauthorized, body: {
  "errors" : [ {
    "status" : 401,
    "message" : "Authentication is required"
  } ]
}
```

Is this something that can be fixed on your side? if not, is there a workaround for this issue?

Thanks!

**Comment by jonesbusy** [comment]
Hi,

Im pretty sure it worked on pro edition.

The copy or move is not available on OSS

From the readme 

There is some on the readme about limitation of OSS Artifactory

**Comment by jonesbusy** [comment]
Will leave this issue open if someone want to investigate or provide a way to reproduce the issue

**Comment by IgnacioMS22** [comment]
Hi @jonesbusy ,

Thanks for the quick response!

I misunderstood how the plugin works and thought it uses the same credentials to upload the artifacts as in the copyArtifacts plugin. I successfully copied the artifacts from Artifactory by setting up anonymous access with read-only permissions.

Note: I know this is not recommended if your repository has confidential information. In my case, the Artifactory server is under a private network with controlled access so there is no security vulnerability.
